### ISSUE TITLE
FAVORITE/SONG NAME doesnt work

### ISSUE THREAD

**Issue by MrCrowCZ** [ciderapp/CiderDeck#13]
Have the latest version of plugin and Cider v 2.5.1_1.

When I hit "favorite" button on my stream deck it doesn't mark the song with the star in the app. 

And another thing is that "song name" worked only once for me and now doesnt show up no matter what. And when it did it was actually kinda useless because the song name was only partialy visible. Would be possible to format the text to more lines? Or have option to formating the view by user?

**Comment by cryptofyre** [comment]
Update to 2.5.3.
