### ISSUE TITLE
Volume Up/Down do not work as expected

### ISSUE THREAD

**Issue by theironraiden** [ciderapp/CiderDeck#7]
Hi,

When using the Stream Deck buttons, instead of their expected behaviour:

- Volume Up switches between 5%, 15% and 35% (my default volume) (Example [Video](https://1drv.ms/v/s!ArJG6w43tjIPxo06bB3d9kUG17C1Ew?e=L0nCSh) notice how the volume slider moves, each move is a button press on stream deck. It's not even consistently switching between the three)

- Volume Down just mutes volume

**Comment by SimplyMerlin** [comment]
This seems to be an issue with exponential volume which you can disable in Settings>Audio. Doesn't seem to be fixable here, pretty sure its an issue with the api.

**Comment by theironraiden** [comment]
Indeed, that fixed it.
Thanks for the response and looking into it.
