### ISSUE TITLE
"Small" feature request.

### ISSUE THREAD

**Issue by HyPeRXKo** [ciderapp/CiderDeck#8]
Hi, love the work you've done on the app and it's a must have transitioning from spotify to apple music from a twitch streamer standpoint.

The streamdeck plugin is a must-have and THE only thing that actually pushed me over the edge before i stopped using spotify, unfortunately, it's lacking 2 thing that the Spotify plugin on the streamdeck has :

1. Different icon selection for play/pause, kinda ruin the whole aesthetic.
2. A repeat playlist/song and shuffle button, extra-useful so i don't have to alt-tab to change it in the middle of the stream.

Also, would be useful to have this plugin in the official streamdeck thing.
Thanks a lot and good luck on the future of your app, it's really a must-have on windows!

**Comment by cryptofyre** [comment]
Both of these have been implemented now, expect it in an upcoming release.

#12
