### ISSUE TITLE
Album Art Not Working

### ISSUE THREAD

**Issue by joshmedeski** [ciderapp/CiderDeck#9]
I enabled the RPC server but the "Album Art" and "Song Name" features don't work. Can you help me troubleshoot or tell me if I'm missing something?

I have the Stream Deck MK.2

**Comment by cryptofyre** [comment]
Please update to the 2.5.0 version of the plugin and follow the instructions to create a token there, that should fix your issue.

(Assuming your app is up to date and not a classic/legacy version)

**Comment by joshmedeski** [comment]
Thanks!
